### PR TITLE
Migrate node sass; bump vue and webpack

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Migrate node-sass to sass-embedded <br> Bump vue, webpack and their plugins version <br> Fix some vue syntax errors
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes {paste the issue here}.
| How to test?      | Apply PR changes then run `npm install` & `npm run build` in Node 14 and Node 16. <br> Check to make sure module works as usual in FO and BO.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by 0x346e3730 — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional we will need your confirmation that the module works as usual :)

**Review by florine2623 — COMMENTED** [review]
Hello @leemyongpakvn ,

The tab **Hook Call Logs** is missing when I install this PR :
Screenshot 2023-05-17 at 14 26 57

Without PR :
Screenshot 2023-05-17 at 14 26 54

Could you check ?
Thanks!

**Comment by leemyongpakvn** [comment]
Hi @florine2623 I found a mismatch between webpack and webpack-cli that makes `npm run build` fails (I haven't seen it 4 months ago :), and fixed it. Please check again.

**Review by hibatallahAouadni — APPROVED** [review]
Hello @leemyongpakvn 

LGTM, QA ✅ 

image

Thanks!

**Comment by nicosomb** [comment]
Thank you @leemyongpakvn !

**Pull request merged**
