### PR TITLE
Remove Node 9, add Node 14, bump webpack and sass version

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Node 9 was EOL 5 years ago. devDependencies are in need of bumping.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes {paste the issue here}.
| How to test?      | Run `npm install` and `npm run build` with Node 14
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Could be a good opportunity to switch to `sass-embedded` as we did in the core but lgtm anyway

**Comment by leemyongpakvn** [comment]
@NeOMakinG I will try to switch to `sass-embeded` after the related PR in the PS core merged.

**Comment by atomiix** [comment]
Can't we just drop support of version < 14? It's been already 8 months that node 12 is not maintained anymore.

**Comment by leemyongpakvn** [comment]
@atomiix Dropped Node 10, 12 as well. Tested successfully and Added Node 16.

**Review by atomiix — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @leemyongpakvn 

Thanks for your PR 🚀 
LGTM, QA ✅ 

[pr-21.webm](https://user-images.githubusercontent.com/23308427/210449246-3eb4088b-b94c-4145-940b-b1fca9357a5a.webm)

Thanks!

**Comment by atomiix** [comment]
Thanks @leemyongpakvn

**Pull request merged**
