### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | When I first used this module I did not know how to build a ZIP neither how to use it. I found the answers but I think it's valuable to add the answers into the README.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | No need for QA

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Is it possible to test JS in this module ? (I think yes), could you maybe try to provide the way in the readme too?

**Comment by matks** [comment]
> Is it possible to test JS in this module ? (I think yes), could you maybe try to provide the way in the readme too?

I did not see any testing capabilities on JS side 🤔

**Comment by NeOMakinG** [comment]
https://github.com/PrestaShop/PrestaShop/pull/19776#issuecomment-664891096

My question is related to this :/

**Comment by PierreRambaud** [comment]
@NeOMakinG You can trigger hook to add custom javascript, but it's only with the PHP process right now

**Comment by PierreRambaud** [comment]
Thanks @matks

**Pull request merged**
